id: I25600553
legacy_id: P006811
ocr_import_info:
  bdrc_scan_id: W1KG21992
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T01:34:51'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T12:51:52.942552+00:00'
last_modified: 2022-08-31 20:52:21.715878
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG21992
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG21992
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྒྱལ་བའི་མཚན་འབུམ་ཀེ་ཏ་ཀའི་ཕྲེང་བ།
  author: དགེ་སློང་བློ་བཟང་སྦྱིན་པ།
statistics:
  ocr_word_mean_confidence_index: 0.6488021055304202
  ocr_word_median_confidence_index: 0.699999988079071
quality: null
bases:
  I1KG22011:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG22011
      total_pages: 746
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG22011.txt
    statistics:
      ocr_word_median_confidence_index: 0.699999988079071
      ocr_word_mean_confidence_index: 0.6488021055304202
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
