id: P006811
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG21992
  title: རྒྱལ་བའི་མཚན་འབུམ་ཀེ་ཏ་ཀའི་ཕྲེང་བ།
  author: ''
  volumes:
    a167bf9e657b48939951f3d35a342068:
      image_group_id: I1KG22011
      title: ''
      volume_number: 1
      total_pages: 746
